CREATE TABLE LOGIN_DETAILS(
    ID          int NOT NULL AUTO_INCREMENT,
    USERNAME    varchar(255),
    PASS_HASH   varchar(255),
    IS_MEDIC    varchar(1) DEFAULT 'N',
    MAIL_CHECK  varchar(1) DEFAULT 'N',
    MAIL_UUID   varchar(255) DEFAULT 'N',
    PRIMARY KEY (ID)
);
CREATE TABLE MEDIC_DETAILS(
    ID          int NOT NULL,
    SNAME       varchar(255),
    LNAME       varchar(255),
    RATING      FLOAT(2,2),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES LOGIN_DETAILS(ID)
);
CREATE TABLE REVIEWS(
    ID          int NOT NULL,
    REVIEW      TEXT,
    PHOTO       LONGBLOB,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES LOGIN_DETAILS(ID)
);
CREATE TABLE PERSONAL_DATA(
    ID          int NOT NULL,
    SUR_NAME    varchar(255),
    LAST_NAME   varchar(255),
    CNP         varchar(20),
    BIRTHDATE   DATE,
    SEX         varchar(1),
    HEIGHT      FLOAT(2,2),
    SGROUP      varchar(2),
    RH          varchar(2),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES LOGIN_DETAILS(ID)
);
CREATE TABLE WEIGHT_HISTORY(
    ID              int NOT NULL,
    WEIGHT_VALUE    FLOAT(3,2),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES LOGIN_DETAILS(ID)
);
CREATE TABLE CONSULTATION_LIST(
    ID              int NOT NULL,
    CONSULTATION    DATE,
    TREATMENT       TEXT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES LOGIN_DETAILS(ID)
);
CREATE TABLE BLOOD_DONATION(
    ID              int NOT NULL,
    DONATION_DATE   DATE,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES LOGIN_DETAILS(ID)
);
